# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* xmlrpc_operation_invoice
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 8.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-07-27 16:32+0000\n"
"PO-Revision-Date: 2017-08-09 00:18+0100\n"
"Last-Translator: <>\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: \n"
"Language: it\n"
"X-Generator: Poedit 1.6.10\n"

#. module: xmlrpc_operation_invoice
#: view:account.invoice:xmlrpc_operation_invoice.view_accont_invoice_export_form
#: view:account.invoice:xmlrpc_operation_invoice.view_accont_invoice_export_supplier_form
msgid "Account Sync"
msgstr "Sincronizza conto"

#. module: xmlrpc_operation_invoice
#: view:account.invoice:xmlrpc_operation_invoice.view_accont_invoice_export_tree
msgid "Account sync"
msgstr "Sincronizza conto"

#. module: xmlrpc_operation_invoice
#: view:account.invoice:xmlrpc_operation_invoice.view_accont_invoice_export_tree
msgid "Account unsync"
msgstr "Conto non sincronizzato"

#. module: xmlrpc_operation_invoice
#: code:addons/xmlrpc_operation_invoice/operation.py:223
#, python-format
msgid "Cannot sync with accounting! (return esit not present"
msgstr ""
"Impossibile sincronizzare con la contabilità! (esito di ritorno non presente)"

#. module: xmlrpc_operation_invoice
#: code:addons/xmlrpc_operation_invoice/operation.py:217
#, python-format
msgid "Comment: %s"
msgstr "Commento: %s"

#. module: xmlrpc_operation_invoice
#: code:addons/xmlrpc_operation_invoice/operation.py:72
#, python-format
msgid "Connect error:"
msgstr "Errore connessione:"

#. module: xmlrpc_operation_invoice
#: code:addons/xmlrpc_operation_invoice/operation.py:216
#, python-format
msgid "Error import invoice:"
msgstr "Errore importando fattura:"

#. module: xmlrpc_operation_invoice
#: view:account.invoice:xmlrpc_operation_invoice.view_accont_invoice_export_form
#: view:account.invoice:xmlrpc_operation_invoice.view_accont_invoice_export_supplier_form
#: view:account.invoice:xmlrpc_operation_invoice.view_accont_invoice_export_tree
msgid "Export in Account"
msgstr "Esporta in contabilità"

#. module: xmlrpc_operation_invoice
#: model:ir.model,name:xmlrpc_operation_invoice.model_account_invoice
msgid "Invoice"
msgstr "Fattura"

#. module: xmlrpc_operation_invoice
#: code:addons/xmlrpc_operation_invoice/operation.py:122
#, python-format
msgid "Invoice must be validated!"
msgstr "La fattura deve essere validata!"

#. module: xmlrpc_operation_invoice
#: view:account.invoice:xmlrpc_operation_invoice.view_account_invoice_sync_search
msgid "Not sync"
msgstr "Non sincronizzato"

#. module: xmlrpc_operation_invoice
#: view:account.invoice:xmlrpc_operation_invoice.view_accont_invoice_export_form
#: view:account.invoice:xmlrpc_operation_invoice.view_accont_invoice_export_tree
msgid "Reset sync"
msgstr "Azzera sincronizzazione"

#. module: xmlrpc_operation_invoice
#: code:addons/xmlrpc_operation_invoice/operation.py:222
#, python-format
msgid "Sync error:"
msgstr "Errore sincronizzazione"

#. module: xmlrpc_operation_invoice
#: model:res.groups,name:xmlrpc_operation_invoice.sync_admin
msgid "XMLRPC Admin"
msgstr "XMLRPC Amministratore"

#. module: xmlrpc_operation_invoice
#: model:ir.model,name:xmlrpc_operation_invoice.model_xmlrpc_operation
msgid "XMLRPC Operation"
msgstr "XMLRPC Operazione "

#. module: xmlrpc_operation_invoice
#: code:addons/xmlrpc_operation_invoice/operation.py:72
#, python-format
msgid "XMLRPC connecting server"
msgstr "XMLRPC server di connessione"

#. module: xmlrpc_operation_invoice
#: code:addons/xmlrpc_operation_invoice/operation.py:121
#, python-format
msgid "XMLRPC sync error"
msgstr "XMLRPC errore sincronizzazione"

#. module: xmlrpc_operation_invoice
#: field:account.invoice,xmlrpc_sync:0
msgid "XMLRPC syncronized"
msgstr "XMLRPC sincronizzato"
